baseURL = 'https://example.org/'
defaultContentLanguage = 'ja'
languageCode = 'ja'
title = 'T2-Lab'
theme = "t2-lab"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
[markup]
  [markup.postCSS]
    includePaths = ["assets/css"]
    [markup.postCSS.options]
      use = ["autoprefixer"]
  [markup.highlight]
    noClasses = false
    style = "github"
    lineNos = true
    lineNumbersInTable = true
